### ISSUE TITLE
Generates machine-dependend seed sizes

### ISSUE THREAD

**Issue by hasufell** [plow-technologies/hspec-golden-aeson#11]
When the golden file is generated on 64bit, but the test is executed on 32bit, hspec won't be able to parse the seed value: https://gitlab.haskell.org/haskell/ghcup-hs/-/jobs/441218#L1670

https://github.com/plow-technologies/hspec-golden-aeson/blob/70312f196d84896ebc8dec04dc3b0817d0310dac/src/Test/Aeson/Internal/GoldenSpecs.hs#L128-L134

In particular: `rSeed <- randomIO`

https://github.com/plow-technologies/hspec-golden-aeson/blob/70312f196d84896ebc8dec04dc3b0817d0310dac/src/Test/Aeson/Internal/GoldenSpecs.hs#L172-L174

**Comment by albertov** [comment]
fd07ee3abd0a43896b86318482882259689cf4fa Should fix this
